# Generated by Django 4.2.4 on 2023-09-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEn', models.CharField(max_length=100)),
                ('nameAr', models.CharField(max_length=100)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stockQuantity', models.IntegerField()),
            ],
        ),
    ]
