# Generated by Django 4.2.4 on 2023-09-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('First Option', 'Pending'), ('Second Option', 'Approved'), ('Third Option', 'Declined'), ('Fourth Option', 'Shipped'), ('Fifth Option', 'Delivered')], max_length=100)),
            ],
        ),
    ]
