# Generated by Django 4.2.4 on 2023-09-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderedCount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(through='website.OrderDetails', to='website.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.ManyToManyField(through='website.OrderDetails', to='website.product'),
        ),
    ]
