# Generated by Django 4.2.4 on 2023-09-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_orderdetails_order_details_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
